language: android
sudo: true
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-23
    - sys-img-armeabi-v7a-android-23
    - extra-android-m2repository

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
  - export ANDROID_NDK_HOME=$HOME/android-ndk-root

script: ./gradlew build connectedCheck
