/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package me.smac89.rps_weezsims;

public class rpslsJNI {
  public final static native String rps(String jarg1, String jarg2);
}
