/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package me.smac89.rps_weezsims;

public class rpsls {
  public static String rps(String p1, String p2) {
    return rpslsJNI.rps(p1, p2);
  }

}
